# Run on push to the main branch or PR

name: Newlib-8266 CI


on:
  push:
  pull_request:


jobs:

  build:
    name: Build Newlib
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Toolchain
      run: |
        mkdir -p $HOME/toolchain/
        pushd $HOME/toolchain/
        for fremote in "package/package_esp8266com_index.template.json" "tools/get.py" ; do
          flocal="${fremote##*/}"
          curl \
            -H "Authentication: ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.VERSION.raw" \
            -o "$flocal" \
            https://api.github.com/repos/esp8266/Arduino/contents/$fremote
        done
        python get.py \
          --no-progress \
          --package-index-json package_esp8266com_index.template.json \
          --tool xtensa-lx106-elf
        popd

    - name: Build
      run: |
        export PATH=$HOME/toolchain/xtensa-lx106-elf/bin/:$PATH
        ./configure \
          CFLAGS_FOR_TARGET="-mlongcalls -Os -g -free -fipa-pta" \
          --target=xtensa-lx106-elf \
          --with-target-subdir=xtensa-lx106-elf \
          --with-newlib \
          --prefix=/newlib \
          --disable-newlib-io-c99-formats \
          --disable-newlib-supplied-syscalls \
          --disable-option-checking \
          --disable-shared \
          --enable-multilib \
          --enable-newlib-nano-formatted-io \
          --enable-newlib-reent-small \
          --enable-target-optspace
        make -j$(nproc) all

    - name: Archive
      run: |
        export PATH=$HOME/toolchain/xtensa-lx106-elf/bin/:$PATH

        for t in . xtensa-lx106-elf/newlib ; do
          mkdir -p $HOME/archive/build-$t
          cp -v $t/config.log $t/config.status $t/Makefile $HOME/archive/build-$t/
        done

        mkdir -p $HOME/archive
        make DESTDIR=$HOME/archive/ install

        pushd $HOME
        time zip \
          --quiet \
          --recurse-paths \
          newlib-${{ github.sha }}.zip archive/
        popd

        mv $HOME/newlib-${{ github.sha }}.zip ./

    - uses: actions/upload-artifact@v4
      with:
        name: newlib-${{ github.sha }}
        path: newlib-${{ github.sha }}.zip
